replicaCount: 1

image:
  repository: elitamsut/helloworld-expressjs
  tag: "v1.0.1-dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

env:
  LISTEN_PORT: 3000
  APP_NAME: "Helloworld ExpressJS App Prod"

