apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helloworld-expressjs.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "helloworld-expressjs.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "helloworld-expressjs.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: LISTEN_PORT
              value: "{{ .Values.env.LISTEN_PORT }}"
            - name: APP_NAME
              value: "{{ .Values.env.APP_NAME }}"
          livenessProbe:
            httpGet:
              path: /
              port: http            # Reference the port by name "http" or directly as {{ .Values.service.port }}
              scheme: HTTP
            initialDelaySeconds: 30 # Adjust based on your app’s startup time
            periodSeconds: 10       # Frequency of liveness checks
          readinessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            initialDelaySeconds: 5  # Start readiness checks shortly after the container starts
            periodSeconds: 10       # Frequency of readiness checks
