apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helloworld-expressjs.fullname" . }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: customer2-app-127-0-0-1.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "helloworld-expressjs.fullname" . }}
                port:
                  number: {{ .Values.service.port }}

